// USERS
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const GET_USERS = 'GET_USERS';
export const FETCHING_USERS = 'FETCHING_USERS';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// POSITIONS
export const GET_POSITIONS = 'GET_POSITIONS';
export const FETCHING_POSITIONS = 'FETCHING_POSITIONS';

// PROJECTS
export const GET_PROJECTS = 'GET_PROJECTS';
export const FETCHING_PROJECTS = 'FETCHING_PROJECTS';
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';

// TASKS
export const ADD_NEW_TASK = 'ADD_NEW_TASK';

// SESSION
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';